# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20161124_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=2000, null=True)),
                ('imageUrl', models.CharField(max_length=100, null=True)),
                ('orders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='betUsers',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
